const SupplierAction = {
    LOADING_APP_START: 'LOADING_APP_START',
    CLOSE_LOADING_APP: 'CLOSE_LOADING_APP',
    LOADING_APP_POPUP_START: 'LOADING_APP_POPUP_START',
    CLOSE_LOADING_APP_POPUP: 'CLOSE_LOADING_APP_POPUP',

   

    FETCH_GET_DATA:'FETCH_GET_DATA',
    FETCH_GET_DATA_SUCCESS:'FETCH_GET_DATA_SUCCESS',
  
    FETCH_GET_DATA_ID: 'FETCH_GET_DATA_ID',
    FETCH_GET_DATA_ID_SUCCESS:'FETCH_GET_DATA_ID_SUCCESS',

    FETCH_UPDATE_DATA_SUCCESS:'FETCH_UPDATE_DATA_SUCCESS',
    FETCH_UPDATE_DATA:'FETCH_UPDATE_DATA',

    FETCH_PUTSATUS_DATA:'FETCH_PUTSATUS_DATA',
    FETCH_PUTSATUS_DATA_SUCCESS:'FETCH_PUTSATUS_DATA_SUCCESS',

    FETCH_ADD_DATA:'FETCH_ADD_DATA',
    FETCH_ADD_DATA_SUCCESS:'FETCH_ADD_DATA_SUCCESS',
///xóa ở detail
    FETCH_POSTDELETE_DATA:'FETCH_POSTDELETE_DATA',
    FETCH_POSTDELETE_DATA_SUCCESS:'FETCH_POSTDELETE_DATA_SUCCESS',
    ///xóa ở list
    FETCH_PUTDELETE_DATA:'FETCH_PUTDELETE_DATA',
    FETCH_PUTDELETE_DATA_SUCCESS:'FETCH_PUTDELETE_DATA_SUCCESS',
    //tìm kiếm
    FETCH_GETSEARCH_DATA:'FETCH_GETSEARCH_DATA',
    FETCH_GETSEARCH_DATA_SUCCESS:'FETCH_GETSEARCH_DATA_SUCCESS',

};

export default SupplierAction;
